### ISSUE TITLE
pass input parameters

### ISSUE THREAD

**Issue by jonpday** [kalenjordan/custom-reports#12]
Would be great to be able to pass parameters (especially date range), similar to the standard Magento functionality.

**Comment by pljspahn** [comment]
Is it just me, or do the date filters not include the start date?

If I filter starting on March 4 and end on March 5, I only see data for March 5. Is it off by one somewhere?

**Comment by rgranadino** [comment]
@pljspahn , keep in mind that dates in the database are stored in UTC. Are you adjusting for that?

**Comment by pljspahn** [comment]
I thought of that after I added a new ticket: https://github.com/kalenjordan/custom-reports/issues/21

`DATE()` won't adjust the time for UTC will it?

**Comment by rgranadino** [comment]
You'll have to manually set the time offset, `DATE_SUB(some_column, INTERVAL 8 HOURS)` or see the MySQL documentation [here](http://dev.mysql.com/doc/refman/5.0/en/date-and-time-functions.html#function_date-add).
