### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by clojens** [kalenjordan/custom-reports#16]
Hi, first off - although I've not yet tried this solution - an advanced party "Thank you" for providing at least some boilerplate functionality for hashing out reports. I'm working with a legacy code base and have found Magento reports very disappointing on many levels. They took the easy road providing date/time always and the rest is muah muah. E.g. sold products, you don't think I want to know *what products?* Magento doesn't and only gives you $$$ figures which is nice and all, but those should be `Financial reports` to begin with. No aggregate functions provided to do group concats, if anything, reports need them. Lazy programmers in a rush create the appearance of sophisticated ideas (and in part Magento has that) to leave a lot (high quantity) often sloppy code in a mediocre language. It would be an embarrassment if anyone would calculate the costs of *that* but I guess entry-level = newbie friendly (hardly) = more wide spread use. The problem with something meant for 'everyone' is that it needs high customization from backend forms for newbie store owners, and one of those things they 'forgot' is reports, not that its made much easier for developers though.. heavy fragmentation of components requires extensive knowledge of core inner workings, extending of resources sometimes native the core, which can have unexpected results (whack-a-mole is something I found to associate with Magento problems constantly, mutable soup like crazy). Oh well, I guess it also generates hours for me to bill but its a drag and I'm always grateful for people skipping past the bullshit and this solution seems to do just that. I'll provide some feedback once I've tried and tested against my current use-case.

Now my rant is done, here's my actual suggestion/request. Please ensure that if you use composer (and you have decided that) is to publish so called tagged version releases in GitHub / git.

You probably will like to use a tool as https://github.com/nvie/gitflow in order to do `git flow release start 0.1.0` and `git flow release finish 0.1.0` after having initialized `git init && git flow init -d` the repository. Doing a `git push --all --tags` (I alias as `git pt`) command, after git flow merged in the branches, will push the tags to remote repo and make them available as 'snapshots' which composer uses. Read the good post on this subject at https://igor.io/2013/01/07/composer-versioning.html for the rationale behind this all. Discourage the use of `*` and `dev-master` as they can easily break software.

Cheers,
Rob

**Comment by kalenjordan** [comment]
Glad to hear it helped.  You can donate by referring customers to https://magemail.co :)

I'm not sure we're going to be able to use tagged releases any time soon.  Sorry man just not able to dedicate much time to this FOSS right now.

**Comment by peterjaap** [comment]
I tagged the last 2 releases. Now at 0.1.4.
