### ISSUE TITLE
No search button

### ISSUE THREAD

**Issue by damienIN** [kalenjordan/custom-reports#19]
I'm not sure if this is an actual issue, but what should we use for the formatting for the fields that we filter like...

{
"filterable": {"Order_Date": "adminhtml/widget_grid_column_filter_datetime"}
}

the block is added to the grid, but I can't use the values I select to filter it.

**Comment by pljspahn** [comment]
Hitting `enter` should trigger the form to submit and apply the filter. Agreed, there should be a button somewhere.

**Comment by kalenjordan** [comment]
Hey guys sorry for the super duper late response but I'm not sure off the top.  I wonder if @rgranadino may be more familiar.

**Comment by rgranadino** [comment]
Sorry for *my* super duper duper late response, I believe there needs to be a check if there's any filtering going on in the configuration. If so don't remove the search button. I think that the proposed PR by @sreichel would add it back but doesn't check if the grid is actually filterable.
