### ISSUE TITLE
Roles - Unable to export as CSV

### ISSUE THREAD

**Issue by jazernorth** [kalenjordan/custom-reports#22]
I've been looking but can't find it ... where can I enable users to export the table report to CSV?  When the user tries they get access denied.

**Comment by kalenjordan** [comment]
Hm not sure haven't used that option myself in a while.  I believe @rgranadino may be more familiar.

**Comment by sreichel** [comment]
It seems it's already fixed with commit https://github.com/kalenjordan/custom-reports/commit/154788482faa655c2a5863121a6b4d9fa3064609.

**Comment by kalenjordan** [comment]
Cool. Ya there were a few recent roles things that I merged.  Shall we close?

**Comment by sreichel** [comment]
Yep. Can be closed.
