### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kalenjordan** [kalenjordan/custom-reports#26]
Given the, ahem, recent events (https://twitter.com/kalenjordan/status/623242258821742592)...should we change the license?  

I think originally we just used the most permissive license possible b/c we wanted to be cool about it, but this seems like an abuse, and I can't really think of a great reason for someone to sell this extension.  Although if someone legit were to approach us about wanting to sell it and they had a valid use case like they wanted to provide higher quality support or whatever around it, we'd totally let them.

Maybe we can change it to the creative commons license which doesn't allow commercial use?
https://tldrlegal.com/license/creative-commons-attribution-noncommercial-noderivs-(cc-nc-nd)#summary

**Comment by ddavidn** [comment]
What about this CC license? https://tldrlegal.com/license/creative-commons-attribution-noncommercial-(cc-nc)

**Comment by kalenjordan** [comment]
Thanks I'll check that out

**Comment by kalenjordan** [comment]
Hey @fbrnc any thoughts?

**Comment by kalenjordan** [comment]
Okay I updated to that one you suggested @ddavidn - good call!
