### ISSUE TITLE
allow for clickable URLs in results

### ISSUE THREAD

**Issue by MarcusWolschon** [kalenjordan/custom-reports#34]
feature request:

allow result values to be clickable URLs.
e.g 
`select concat('<a href="/index.php/admin/sales_order/view/order_id/', order_id, '">order #', order_id, '</a>') from  sales_flat_order_item`

**Comment by peterjaap** [comment]
See PR https://github.com/kalenjordan/custom-reports/pull/46

**Comment by kalenjordan** [comment]
You sexy animal @peterjaap thanks!!!

**Comment by MarcusWolschon** [comment]
Yes, you can click them.
No they are not regular links that you can e.g. open in a new tab.
