### ISSUE TITLE
Add support for MySQL variables

### ISSUE THREAD

**Issue by mpchadwick** [kalenjordan/custom-reports#38]
I've already started working on this and can submit a PR if you're interested. 

The idea is that before [this](https://github.com/kalenjordan/custom-reports/blob/17a4b9a5721903e27f1e7921abf14ca6353fb37b/app/code/community/Clean/SqlReports/Model/Report.php#L30-L33) happens we set any variables that are configured which can then be used in the `sql_query`.

We can build the `SET` statement from a string of JSON as is done for the Chart Configuration and Grid Configuration.

e.g.

```json
{
    "a": "0",
    "last_order": "0"
}
```

**Comment by mpchadwick** [comment]
Actually, in playing around further this doesn't seem like it would be that useful because you can assign values to variables in statements other than `SET`s (e.g `SELECT`). I'm closing this.

**Comment by kalenjordan** [comment]
Thanks buddy - appreciate it.

On Fri, Oct 30, 2015 at 6:35 PM, Max Chadwick <notifications@github.com>
wrote:

> Actually, in playing around further this doesn't seem like it would be
> that useful because you can assign values to variables in statements other
> than SETs (e.g SELECT). I'm closing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalenjordan/custom-reports/issues/38#issuecomment-152683957>
> .
>



-- 
Kalen Jordan
Founder, MageMail

MageMail <https://magemail.co> | Magento Podcast <http://magetalk.com/>
