### ISSUE TITLE
Duplicate Header Content-Type (PHP-FPM) issue

### ISSUE THREAD

**Issue by mpchadwick** [kalenjordan/custom-reports#40]
I'm not necessarily saying this is an issue with the module, as this not an issue I've spent enough time on to have an opinion on, but requests to `getJsonAction()` lead to a 500 error in PHP-FPM with the following error in the Apache logs.

```
FastCGI: comm with server "/usr/lib/cgi-bin/php5-fcgi" aborted: error parsing headers: duplicate header 'Content-Type'
```

This is a [pretty common](https://www.google.com/search?q=magento+duplicate+content+type) error in Magento / PHP-FPM.

If you're running into that issue you'll get a 200 if you comment out [this line](https://github.com/kalenjordan/custom-reports/blob/2ed426b0434462d532b67f400215804e49a584c2/app/code/community/Clean/SqlReports/controllers/Adminhtml/ReportController.php#L1240).

I'm not suggesting that that is the correct solution (nor even that the issue lies in this module and is not a Magento core issue), simply putting this out there as an issue in case anyone else runs into it.

**Comment by peterjaap** [comment]
See https://github.com/jreinke/magento-admin-launcher/issues/7
