### ISSUE TITLE
Where can i learn Magento SQL queries?

### ISSUE THREAD

**Issue by danielchicote** [kalenjordan/custom-reports#43]
Hello, im trying to extract some datas and my knowledge of SQL queries and the magento database are very limited. Do you know any Magento book or tutorials page where i can learn the relations of the database?

For example i need an invoice report with #Invoice / Date / Name / VAT tax / Import
, but im losted when i try to extract the tax vat, that i supponse is on customer_address_entity_varchar table. :(

<code>SELECT increment_id AS 'Invoice', created_at AS 'Date', billing_name AS 'Name', grand_total AS 'Total'
FROM `sales_flat_invoice_grid` </code>

**Comment by philwinkle** [comment]
I feel your pain @danielchicote but this is not an issue for the repository. Perhaps ask over on the Magento forums for some help. https://community.magento.com/

**Comment by kalenjordan** [comment]
Thanks @philwinkle for the assist!

**Comment by danielchicote** [comment]
```
SELECT increment_id AS 'Invoice number', created_at AS 'Date', billing_name AS 'Client name', vat_id AS `VAT`, company AS 'Company', grand_total AS 'Import'
FROM `sales_flat_invoice_grid`
INNER JOIN `sales_flat_order_address`  on `vat_id`
```
:+1:
