### ISSUE TITLE
Clilckable URL does not work in some cases

### ISSUE THREAD

**Issue by peterjaap** [kalenjordan/custom-reports#51]

**Comment by peterjaap** [comment]
When a column alias is used, the getRowUrl() function does not retrieve it correctly. Avoid using aliases for clickable row URL option for now.

**Comment by sreichel** [comment]
How about using grid configuration for clickable URLs? It would also allow multiple clickable columns.

From you example in #46:

```
{"clickable": {
    "entity_id": {
        "*/sales_order/view/order_id": "entity_id"
    },
    "increment_id": {
        "*/sales_order/view/order_id": "entity_id"
    }
}}
```
