### ISSUE TITLE
Why are search and reset filter buttons removed?

### ISSUE THREAD

**Issue by ProxiBlue** [kalenjordan/custom-reports#58]
Hi,

Whey, here: custom-reports/app/code/community/Clean/SqlReports/Block/Adminhtml/Customreport/View/Grid.php are the buttons removed in the _prepareLayout method ?

Without the buttons, doing/using the filters are not possible.
I cannot figure out why this was done, so maybe I am missing something?

-Lucas

**Comment by peterjaap** [comment]
You're right, I have no idea. Just tested and works fine. I've removed these calls in 0.1.11.
