### ISSUE TITLE
Getting Error when logging in admin

### ISSUE THREAD

**Issue by pushpendra07** [kalenjordan/custom-reports#60]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cleansql_report' doesn't exist, query was: SELECT `main_table`.\* FROM `cleansql_report` AS `main_table` ORDER BY title ASC

**Comment by peterjaap** [comment]
Have you cleared the cache?

**Comment by pushpendrabkn** [comment]
No, I don't clear the cache by admin side, but I run magento cleanup file and trying to login then getting this error.

**Comment by peterjaap** [comment]
What do you mean with 'Magento cleanup file' ? Try using Magerun to clear
the cache.

Op di 5 apr. 2016 om 11:19 schreef pushpendrabkn <notifications@github.com>:

**Comment by pushpendrabkn** [comment]
@peterjaap I cannot access admin after installed this plugin then I use magento cleanup file to set folder and files permission and rename the cache folder also but it's not working.

**Comment by pushpendrabkn** [comment]
Hi, Can you help me on this.

**Comment by sreichel** [comment]
Seems not extension realted ... due to lack of feedback close?

**Comment by husseycoding** [comment]
FYI, I saw this too - resolved by a cache clear.
