### ISSUE TITLE
Magento2

### ISSUE THREAD

**Issue by joshspivey** [kalenjordan/custom-reports#61]
Do you have plans on porting this over to Magento 2?

**Comment by MarcusWolschon** [comment]
Is there anything we could help with for Magento 2?

**Comment by peterjaap** [comment]
Yes, porting it would be nice! 😆

**Comment by MarcusWolschon** [comment]
Sorry, absolutely no experience with writing completely new Magento plugins.

**Comment by erikhansen** [comment]
If anyone does port this to Magento 2, or finds a similar extension for Magento 2, I'd love to know about this.
